//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yachaydi_marketEntities : DbContext
    {
        public yachaydi_marketEntities()
            : base("name=yachaydi_marketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horario_Negocio> Horario_Negocio { get; set; }
        public virtual DbSet<Negocio> Negocio { get; set; }
        public virtual DbSet<Negocio_Login> Negocio_Login { get; set; }
        public virtual DbSet<Negocio_Producto> Negocio_Producto { get; set; }
        public virtual DbSet<PalabrasClave> PalabrasClave { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
    }
}
