//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int IdAlerta { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdNegocio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public Nullable<bool> Tomado { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Negocio Negocio { get; set; }
    }
}
