//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Negocio
    {
        public int id_Negocio { get; set; }
        public byte dia_Laboral { get; set; }
        public string dia_nombre { get; set; }
        public byte Hora_Inicio { get; set; }
        public byte Minutos_Inicio { get; set; }
        public byte Hora_Fin { get; set; }
        public byte Minutos_Fin { get; set; }
    
        public virtual Negocio Negocio { get; set; }
    }
}
