//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_PalabrasClave
    {
        public int id_Negocio { get; set; }
        public string caracter_PalabraClave { get; set; }
        public string texto_PalabraClave { get; set; }
    
        public virtual Negocio Negocio { get; set; }
    }
}
