//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio()
        {
            this.Alerta = new HashSet<Alerta>();
            this.Alerta1 = new HashSet<Alerta>();
            this.Horario_Negocio = new HashSet<Horario_Negocio>();
            this.Negocio_Login = new HashSet<Negocio_Login>();
            this.Negocio_Producto = new HashSet<Negocio_Producto>();
            this.PalabrasClave = new HashSet<PalabrasClave>();
        }
    
        public int id_Negocio { get; set; }
        public string email_Negocio { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
        public string Direccion_texto { get; set; }
        public string Referencia { get; set; }
        public string Direccion_Latitud { get; set; }
        public string Direccion_Longitud { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Negocio> Horario_Negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Login> Negocio_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Producto> Negocio_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalabrasClave> PalabrasClave { get; set; }
    }
}
