//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio()
        {
            this.Horario_Negocio = new HashSet<Horario_Negocio>();
            this.Negocio_Producto = new HashSet<Negocio_Producto>();
        }
    
        public string email_Negocio { get; set; }
        public string Nombre { get; set; }
        public string Direccion_texto { get; set; }
        public string Direccion_Latitud { get; set; }
        public string Direccion_Longitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Negocio> Horario_Negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Producto> Negocio_Producto { get; set; }
    }
}
