//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachay.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Propuesta
    {
        public int IdPedido { get; set; }
        public int IdNegocio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Negocio Negocio { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
